/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *image1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *hbuttonbox2;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), "Password Management");
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  image1 = create_pixmap (window1, "tt.png");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (vbox1), image1, FALSE, TRUE, 0);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (fixed1, 400, 130);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 176, 16);
  gtk_widget_set_size_request (entry1, 200, 30);
  gtk_tooltips_set_tip (tooltips, entry1, "Enter College Code (4 digits)", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry1), 4);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 176, 72);
  gtk_widget_set_size_request (entry2, 200, 30);
  gtk_tooltips_set_tip (tooltips, entry2, "Enter new password (between 6 and 15 characters)", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry2), 15);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);

  label2 = gtk_label_new ("<span foreground=\"#54754F\"><b>Password</b></span>");
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 16, 72);
  gtk_widget_set_size_request (label2, 140, 30);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  label1 = gtk_label_new ("<span foreground=\"#54754F\"><b>College Code</b></span>");
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 16, 16);
  gtk_widget_set_size_request (label1, 140, 30);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox2, FALSE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox2), 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);

  button1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) window1, "delete_event",
                            G_CALLBACK (on_window1_delete_event),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) button1, "clicked",
                            G_CALLBACK (on_button1_clicked),
                            GTK_OBJECT (button1));
  g_signal_connect_swapped ((gpointer) button2, "clicked",
                            G_CALLBACK (on_button2_clicked),
                            GTK_OBJECT (button2));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT_NO_REF (window1, tooltips, "tooltips");

  return window1;
}

