#ifndef _INTERFACE_H_
#define _INTERFACE_H_
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);

#endif /* _INTERFACE_H_ */
